# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/btcd"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "=1.11.1"

[[constraint]]
  name = "github.com/rs/cors"
  version = "^1.6.0"

[[constraint]]
  name = "github.com/danil-lashin/iavl"
  branch = "master"

[[constraint]]
  name = "github.com/tendermint/tendermint"
  version = "0.28.0"

[[constraint]]
  name = "github.com/MinterTeam/go-amino"
  version = "=v0.14.1-m"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/check.v1"

[[constraint]]
  name = "github.com/miguelmota/go-ethereum-hdwallet"
  revision = "8af197af5b280f901269c2d1ad0da4ae994063ee"

[[override]]
  name = "golang.org/x/crypto"
  revision = "505ab145d0a99da450461ae2c1a9f6cd10d1f447"

[prune]
  go-tests = true
  unused-packages = true
